branch-defaults:
  master:
    environment: xaveng
global:
  application_name: xaveng
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: ap-northeast-2
  profile: eb-cli
  sc: git
